name: Isaac's Blog
url: #
description: We see things as we are.
twitter: IsaacXen

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
extensions: ["fenced_code_blocks"]